<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!-- Generated by TLex Lexicography Software (build Mar 20 2022 23:17:30) -->
<!-- Generated on Wed May 18 12:25:00 2022 -->
<!-- TshwaneDJe HLT - XML version 1.10 -->
<!-- ExportListValuesByText: ON -->
<!-- UseZeroWidthSpacesToPreventConversionOfPCDataToElements: OFF -->
<!DOCTYPE tshwanelexicon [
<!ELEMENT tshwanelexicon (dtd,styleset*,Dictionary)>
<!ELEMENT dtd (specialtypes?,dtdlist*,xreftypes*)>
<!ELEMENT dtdlist (dtdlistitem*,listlabelset*)>
<!ELEMENT dtdlistitem EMPTY>
<!ELEMENT listlabelset (listlabel*)>
<!ELEMENT listlabel EMPTY>
<!ELEMENT xreftypes (xreftype*,xreflabelset*)>
<!ELEMENT xreftype EMPTY>
<!ELEMENT xreflabelset (xreflabel*)>
<!ELEMENT xreflabel EMPTY>
<!ELEMENT specialtypes (special*)>
<!ELEMENT special EMPTY>
<!ELEMENT styleset (order,style*)>
<!ELEMENT order (order_element*)>
<!ELEMENT order_element (order_item*)>
<!ELEMENT order_item EMPTY>
<!ELEMENT style (style_autonumber*)>
<!ELEMENT style_autonumber EMPTY>
<!ELEMENT Dictionary (Language+)>
<!ELEMENT Language (Lemma*)>
<!ELEMENT Lemma (LemmaRef*,ExpressionList*,ArgUnit+)>
<!ELEMENT Sense (Definition+,Example+,SenseRef*)>
<!ELEMENT Example EMPTY>
<!ELEMENT ExpressionList (Expression*)>
<!ELEMENT Definition EMPTY>
<!ELEMENT LemmaRef (reflemma*)>
<!ELEMENT reflemma (refsense*)>
<!ELEMENT refsense EMPTY>
<!ELEMENT ArgUnit (LemmaFeature*,ArgStructure+,Sense+,Constructions*,ArgUnitRef*,Clue*)>
<!ELEMENT LemmaFeature (Clue*)>
<!ELEMENT ArgStructure (ArgPosition+,LemmaFeature*)>
<!ELEMENT ArgPosition (Argument+,PositionState?)>
<!ELEMENT Argument (AFeature)>
<!ELEMENT PositionState EMPTY>
<!ELEMENT AFeature EMPTY>
<!ELEMENT Clue EMPTY>
<!ELEMENT Constructions (Passive*,Impers*)>
<!ELEMENT Passive EMPTY>
<!ELEMENT Impers EMPTY>
<!ELEMENT SenseRef EMPTY>
<!ELEMENT ArgUnitRef EMPTY>
<!ELEMENT Expression EMPTY>
<!ATTLIST dtdlist id CDATA #REQUIRED>
<!ATTLIST dtdlist name CDATA #REQUIRED>
<!ATTLIST dtdlistitem id CDATA #REQUIRED>
<!ATTLIST dtdlistitem name CDATA #REQUIRED>
<!ATTLIST listlabelset name CDATA #REQUIRED>
<!ATTLIST listlabel listitemid CDATA #REQUIRED>
<!ATTLIST listlabel name CDATA #REQUIRED>
<!ATTLIST xreftype id CDATA #REQUIRED>
<!ATTLIST xreftype name CDATA #REQUIRED>
<!ATTLIST xreflabelset name CDATA #REQUIRED>
<!ATTLIST xreflabel xreftypeid CDATA #REQUIRED>
<!ATTLIST xreflabel labels CDATA #REQUIRED>
<!ATTLIST xreflabel labelp CDATA #REQUIRED>
<!ATTLIST reflemma lemmaid CDATA #REQUIRED>
<!ATTLIST reflemma type CDATA #REQUIRED>
<!ATTLIST refsense senseid CDATA #REQUIRED>
<!ATTLIST special type CDATA #REQUIRED>
<!ATTLIST special section CDATA #REQUIRED>
<!ATTLIST special attr CDATA #REQUIRED>
<!ATTLIST special elem CDATA #REQUIRED>
<!ATTLIST styleset name CDATA #IMPLIED>
<!ATTLIST order_element elementname CDATA #REQUIRED>
<!ATTLIST order_item type CDATA #REQUIRED>
<!ATTLIST order_item name CDATA #REQUIRED>
<!ATTLIST order_item visible CDATA #REQUIRED>
<!ATTLIST style type CDATA #IMPLIED>
<!ATTLIST style elementname CDATA #IMPLIED>
<!ATTLIST style attributename CDATA #IMPLIED>
<!ATTLIST style style CDATA #IMPLIED>
<!ATTLIST style font CDATA #IMPLIED>
<!ATTLIST style fontsize CDATA #IMPLIED>
<!ATTLIST style bold CDATA #IMPLIED>
<!ATTLIST style italic CDATA #IMPLIED>
<!ATTLIST style underline CDATA #IMPLIED>
<!ATTLIST style superscript CDATA #IMPLIED>
<!ATTLIST style subscript CDATA #IMPLIED>
<!ATTLIST style smallcaps CDATA #IMPLIED>
<!ATTLIST style caps CDATA #IMPLIED>
<!ATTLIST style colourf CDATA #IMPLIED>
<!ATTLIST style colourb CDATA #IMPLIED>
<!ATTLIST style beforei CDATA #IMPLIED>
<!ATTLIST style afteri CDATA #IMPLIED>
<!ATTLIST style beforeo CDATA #IMPLIED>
<!ATTLIST style aftero CDATA #IMPLIED>
<!ATTLIST style beforeg CDATA #IMPLIED>
<!ATTLIST style afterg CDATA #IMPLIED>
<!ATTLIST style between CDATA #IMPLIED>
<!ATTLIST style_autonumber type CDATA #IMPLIED>
<!ATTLIST style_autonumber always CDATA #IMPLIED>
<!ATTLIST style_autonumber breadth CDATA #IMPLIED>
<!ATTLIST style_autonumber depth CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary Name CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary Description CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary CreatedBy CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary Copyright CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary URL CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary SoundPath CDATA #IMPLIED>
<!ATTLIST Dictionary id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language Name CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#IMPLIED,ltr -->
<!ATTLIST Language Options CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language AlphabetQuicklinks CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language SearchScript CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language ClickScript CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language xml:lang CDATA #IMPLIED>
<!ATTLIST Language id CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Incomplete CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#REQUIRED,ltr -->
<!ATTLIST Lemma LemmaSign CDATA #REQUIRED>
<!-- ATTDATA NDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma HomonymNumber CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Notes CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Frequency CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#DATECHANGED,ltr -->
<!ATTLIST Lemma Modified CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#DATECREATED,ltr -->
<!ATTLIST Lemma Created CDATA #IMPLIED>
<!ATTLIST Lemma id CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#AUTONUMBER,ltr -->
<!ATTLIST Sense SenseNumber CDATA #IMPLIED>
<!ATTLIST Sense id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Example Example CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Example Translation CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Example Source CDATA #IMPLIED>
<!ATTLIST Example id CDATA #IMPLIED>
<!ATTLIST ExpressionList id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#REQUIRED,ltr -->
<!ATTLIST Definition Definition CDATA #REQUIRED>
<!ATTLIST Definition id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST LemmaRef LemmaRef CDATA #IMPLIED>
<!ATTLIST LemmaRef id CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#AUTONUMBER,ltr -->
<!ATTLIST ArgUnit ArgUnitNr CDATA #IMPLIED>
<!ATTLIST ArgUnit id CDATA #IMPLIED>
<!-- ATTDATA LDATA,ReflForm,#IMPLIED,ltr -->
<!ATTLIST LemmaFeature ReflForm CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST LemmaFeature NegForm CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST LemmaFeature FlexForm CDATA #IMPLIED>
<!ATTLIST LemmaFeature id CDATA #IMPLIED>
<!ATTLIST ArgStructure id CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#AUTONUMBER,ltr -->
<!ATTLIST ArgPosition PositionNr CDATA #IMPLIED>
<!ATTLIST ArgPosition id CDATA #IMPLIED>
<!-- ATTDATA LDATA,POS,#IMPLIED,ltr -->
<!ATTLIST Argument POS CDATA #IMPLIED>
<!ATTLIST Argument id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST PositionState PositionState CDATA #IMPLIED>
<!ATTLIST PositionState id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST AFeature Gram CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST AFeature Sem CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST AFeature Clue CDATA #IMPLIED>
<!ATTLIST AFeature id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Clue Clue CDATA #IMPLIED>
<!ATTLIST Clue id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Constructions Passive CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Constructions Impers CDATA #IMPLIED>
<!ATTLIST Constructions id CDATA #IMPLIED>
<!ATTLIST Passive id CDATA #IMPLIED>
<!ATTLIST Impers id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST SenseRef SenseRef CDATA #IMPLIED>
<!ATTLIST SenseRef id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST ArgUnitRef ArgUnitRef CDATA #IMPLIED>
<!ATTLIST ArgUnitRef id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Expression LemmaSign CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Expression Definition CDATA #IMPLIED>
<!ATTLIST Expression id CDATA #IMPLIED>
<!ENTITY ndash "–">
<!ENTITY mdash "—">
<!ENTITY lsquo "‘">
<!ENTITY rsquo "’">
<!ENTITY ldquo "“">
<!ENTITY rdquo "”">
<!ENTITY bull "•">
<!ENTITY hellip "…">
<!ENTITY trade "™">
<!ENTITY dagger "†">
<!ENTITY Dagger "‡">
<!ENTITY lsaquo "‹">
<!ENTITY rsaquo "›">
<!ENTITY sp " ">
<!ENTITY nbsp " ">
<!ENTITY ensp " ">
<!ENTITY emsp " ">
<!ENTITY pound "£">
<!ENTITY copy "©">
<!ENTITY reg "®">
<!ENTITY tshwanelex__list__seperator ";">
]>
<tshwanelexicon>
<dtd>
	<specialtypes>
		<special type="1" section="2" attr="Frequency" elem="Lemma"/>
		<special type="2" section="2" attr="" elem="Sense"/>
		<special type="3" section="2" attr="LemmaSign" elem="Lemma"/>
		<special type="4" section="2" attr="Notes" elem="Lemma"/>
	</specialtypes>
	<dtdlist id="1" name="Usage label">
		<listlabelset name="Romanian">
		</listlabelset>
	</dtdlist>
	<dtdlist id="2" name="Part of speech">
		<dtdlistitem id="3" name="noun"/>
		<dtdlistitem id="4" name="pl noun"/>
		<dtdlistitem id="5" name="verb"/>
		<dtdlistitem id="6" name="verb transitive"/>
		<dtdlistitem id="7" name="verb intransitive"/>
		<dtdlistitem id="8" name="adjective"/>
		<dtdlistitem id="9" name="adverb"/>
		<dtdlistitem id="10" name="abbreviation"/>
		<dtdlistitem id="11" name="pronoun"/>
		<dtdlistitem id="12" name="conjunction"/>
		<dtdlistitem id="13" name="interjection"/>
		<dtdlistitem id="14" name="concord"/>
		<dtdlistitem id="15" name="idiom"/>
		<dtdlistitem id="16" name="proverb"/>
		<listlabelset name="Romanian">
			<listlabel listitemid="3" name="noun"/>
			<listlabel listitemid="4" name="pl noun"/>
			<listlabel listitemid="5" name="verb"/>
			<listlabel listitemid="6" name="verb transitive"/>
			<listlabel listitemid="7" name="verb intransitive"/>
			<listlabel listitemid="8" name="adjective"/>
			<listlabel listitemid="9" name="adverb"/>
			<listlabel listitemid="10" name="abbreviation"/>
			<listlabel listitemid="11" name="pronoun"/>
			<listlabel listitemid="12" name="conjunction"/>
			<listlabel listitemid="13" name="interjection"/>
			<listlabel listitemid="14" name="concord"/>
			<listlabel listitemid="15" name="idiom"/>
			<listlabel listitemid="16" name="proverb"/>
		</listlabelset>
	</dtdlist>
	<dtdlist id="17" name="ReflForm">
		<dtdlistitem id="18" name="își"/>
		<dtdlistitem id="28" name="îi"/>
		<dtdlistitem id="27" name="o"/>
		<dtdlistitem id="19" name="se"/>
	</dtdlist>
	<dtdlist id="20" name="POS">
		<dtdlistitem id="21" name="GN"/>
		<dtdlistitem id="26" name="V"/>
		<dtdlistitem id="22" name="GAdj"/>
		<dtdlistitem id="23" name="GP"/>
		<dtdlistitem id="24" name="GV"/>
		<dtdlistitem id="25" name="GAdv"/>
	</dtdlist>
	<xreftypes>
		<xreftype id="1" name="Equivalence"/>
		<xreftype id="2" name="See"/>
		<xreftype id="3" name="Synonym"/>
		<xreftype id="4" name="Antonym"/>
		<xreftype id="5" name="Compare"/>
		<xreflabelset name="English">
			<xreflabel xreftypeid="1" labels="=" labelp="="/>
			<xreflabel xreftypeid="2" labels="SEE" labelp="SEE"/>
			<xreflabel xreftypeid="3" labels="SYNONYM" labelp="SYNONYMS"/>
			<xreflabel xreftypeid="4" labels="ANTONYM" labelp="ANTONYMS"/>
			<xreflabel xreftypeid="5" labels="COMPARE" labelp="COMPARE"/>
		</xreflabelset>
	</xreftypes>
</dtd>
<styleset name="Default styles">
	<order>
		<order_element elementname="Dictionary">
			<order_item type="element" name="Language" visible="1"/>
			<order_item type="attribute" name="Name" visible="1"/>
			<order_item type="attribute" name="Description" visible="1"/>
			<order_item type="attribute" name="CreatedBy" visible="1"/>
			<order_item type="attribute" name="Copyright" visible="1"/>
			<order_item type="attribute" name="URL" visible="1"/>
			<order_item type="attribute" name="SoundPath" visible="1"/>
		</order_element>
		<order_element elementname="Language">
			<order_item type="element" name="Lemma" visible="1"/>
			<order_item type="attribute" name="Name" visible="1"/>
			<order_item type="attribute" name="Options" visible="1"/>
			<order_item type="attribute" name="AlphabetQuicklinks" visible="1"/>
			<order_item type="attribute" name="SearchScript" visible="1"/>
			<order_item type="attribute" name="ClickScript" visible="1"/>
			<order_item type="attribute" name="xml:lang" visible="1"/>
		</order_element>
		<order_element elementname="Lemma">
			<order_item type="attribute" name="LemmaSign" visible="1"/>
			<order_item type="attribute" name="HomonymNumber" visible="1"/>
			<order_item type="element" name="ArgUnit" visible="1"/>
			<order_item type="element" name="ExpressionList" visible="1"/>
			<order_item type="element" name="LemmaRef" visible="1"/>
			<order_item type="attribute" name="Incomplete" visible="1"/>
			<order_item type="attribute" name="Notes" visible="1"/>
			<order_item type="attribute" name="Frequency" visible="0"/>
			<order_item type="attribute" name="Modified" visible="1"/>
			<order_item type="attribute" name="Created" visible="1"/>
		</order_element>
		<order_element elementname="Sense">
			<order_item type="attribute" name="SenseNumber" visible="1"/>
			<order_item type="element" name="Definition" visible="1"/>
			<order_item type="element" name="Example" visible="1"/>
			<order_item type="element" name="SenseRef" visible="1"/>
		</order_element>
		<order_element elementname="Example">
			<order_item type="attribute" name="Example" visible="1"/>
			<order_item type="attribute" name="Translation" visible="1"/>
			<order_item type="attribute" name="Source" visible="1"/>
		</order_element>
		<order_element elementname="ExpressionList">
			<order_item type="element" name="Expression" visible="1"/>
		</order_element>
		<order_element elementname="Definition">
			<order_item type="attribute" name="Definition" visible="1"/>
		</order_element>
		<order_element elementname="LemmaRef">
			<order_item type="attribute" name="LemmaRef" visible="1"/>
		</order_element>
		<order_element elementname="ArgUnit">
			<order_item type="attribute" name="ArgUnitNr" visible="1"/>
			<order_item type="element" name="LemmaFeature" visible="1"/>
			<order_item type="element" name="ArgStructure" visible="1"/>
			<order_item type="element" name="Sense" visible="1"/>
			<order_item type="element" name="Constructions" visible="1"/>
			<order_item type="element" name="ArgUnitRef" visible="1"/>
			<order_item type="element" name="Clue" visible="1"/>
		</order_element>
		<order_element elementname="LemmaFeature">
			<order_item type="attribute" name="NegForm" visible="1"/>
			<order_item type="attribute" name="ReflForm" visible="1"/>
			<order_item type="element" name="Clue" visible="1"/>
			<order_item type="attribute" name="FlexForm" visible="1"/>
		</order_element>
		<order_element elementname="ArgStructure">
			<order_item type="element" name="LemmaFeature" visible="1"/>
			<order_item type="element" name="ArgPosition" visible="1"/>
		</order_element>
		<order_element elementname="ArgPosition">
			<order_item type="attribute" name="PositionNr" visible="1"/>
			<order_item type="element" name="PositionState" visible="1"/>
			<order_item type="element" name="Argument" visible="1"/>
		</order_element>
		<order_element elementname="Argument">
			<order_item type="attribute" name="POS" visible="1"/>
			<order_item type="element" name="AFeature" visible="1"/>
		</order_element>
		<order_element elementname="Clue">
			<order_item type="attribute" name="Clue" visible="1"/>
		</order_element>
		<order_element elementname="PositionState">
			<order_item type="attribute" name="PositionState" visible="1"/>
		</order_element>
		<order_element elementname="AFeature">
			<order_item type="attribute" name="Gram" visible="1"/>
			<order_item type="attribute" name="Sem" visible="1"/>
			<order_item type="attribute" name="Clue" visible="1"/>
		</order_element>
		<order_element elementname="Constructions">
			<order_item type="element" name="Passive" visible="1"/>
			<order_item type="element" name="Impers" visible="1"/>
			<order_item type="attribute" name="Passive" visible="1"/>
			<order_item type="attribute" name="Impers" visible="1"/>
		</order_element>
		<order_element elementname="Passive">
		</order_element>
		<order_element elementname="Impers">
		</order_element>
		<order_element elementname="SenseRef">
			<order_item type="attribute" name="SenseRef" visible="1"/>
		</order_element>
		<order_element elementname="ArgUnitRef">
			<order_item type="attribute" name="ArgUnitRef" visible="1"/>
		</order_element>
		<order_element elementname="Expression">
			<order_item type="attribute" name="LemmaSign" visible="1"/>
			<order_item type="attribute" name="Definition" visible="1"/>
		</order_element>
	</order>
	<style type="element" elementname="Lemma" attributename="-1" style="Arial,10.000000,-1,-1,-1,-1,-1,-1,-1,000000,FFFFFF,,,,,,,,1,0,0.000000,-5.000000,5.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="LemmaSign" style=",-1.000000,1,-1,-1,-1,-1,-1,-1,000070,,,,,,,,,1,0,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="HomonymNumber" style=",10.000000,1,-1,-1,1,-1,-1,-1,000070,,,,,,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="Notes" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,FD8668,, {,},,,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="Frequency" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,(,) ,,,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="Modified" style=",9.000000,-1,-1,-1,-1,-1,-1,-1,888888,, [,],,,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="Created" style=",9.000000,-1,1,-1,-1,-1,-1,-1,888888,, [,],,,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Sense" attributename="-1" style="MS UI Gothic,-1.000000,-1,-1,-1,-1,-1,-1,-1,062A06,,,,,,,,,1,0,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="LemmaRef" attributename="-1" style=",-1.000000,1,-1,-1,-1,-1,-1,-1,0C5252,,,,,, ,, ,0,0,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="ExpressionList" attributename="-1" style=",-1.000000,1,-1,-1,-1,-1,-1,-1,880502,,,,Expresii:,,,,,1,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Example" attributename="-1" style="Times New Roman,11.000000,-1,-1,-1,-1,-1,-1,-1,706D10,,,,,,:,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Example" attributename="Example" style=",-1.000000,-1,1,-1,-1,-1,-1,-1,,, ,,,//,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Example" attributename="Translation" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,, ,,,,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Example" attributename="Source" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,, ,,,,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Definition" attributename="-1" style="Times New Roman,-1.000000,-1,-1,-1,-1,-1,-1,-1,128181,,,,,,,,;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Definition" attributename="Definition" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,, ,,,,,,,0,0,0.000000,0.000000,30.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Sense" attributename="SenseNumber" style=",-1.000000,1,-1,-1,-1,-1,-1,-1,,,,., ,,,,,0,0,0.000000,0.000000,30.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000," >
		<style_autonumber type="2" always="0" breadth="1" depth="0" />
	</style>
	<style type="element" elementname="ArgUnit" attributename="-1" style=",-1.000000,0,-1,-1,-1,-1,-1,-1,,,,,,,,, ,0,0,0.000000,0.000000,30.000000,0.000000,12.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="LemmaFeature" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,,    V [,],,,&quot;,&quot;,0,1,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="ArgStructure" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,,,,,,&quot;,&quot;,1,0,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="ArgPosition" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,,,,,,&quot;,&quot;,0,0,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Argument" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,,,,,, / ,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="ArgUnit" attributename="ArgUnitNr" style=",-1.000000,1,-1,-1,-1,-1,-1,-1,,,,, ,.,,,&quot;, &quot;,1,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000," >
		<style_autonumber type="5" always="1" breadth="0" depth="0" />
		<style_autonumber type="1" always="1" breadth="0" depth="0" />
	</style>
	<style type="attribute" elementname="LemmaFeature" attributename="ReflForm" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,, ,,,,&quot;, &quot;,0,0,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="LemmaFeature" attributename="NegForm" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,, ,,,,&quot;, &quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Clue" attributename="-1" style="Times New Roman,10.000000,1,-1,-1,-1,-1,-1,-1,,,Obs.,,,,,,&quot;,&quot;,1,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Clue" attributename="Clue" style="Times New Roman,10.000000,-1,-1,-1,-1,-1,-1,-1,,,,, ,,,,&quot;, &quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Argument" attributename="POS" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,, ,,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="ArgPosition" attributename="PositionNr" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,., ,,,,&quot;, &quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Language" attributename="SearchScript" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,, ,,,,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Language" attributename="ClickScript" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,, ,,,,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="PositionState" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,,,,,,&quot;,&quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="PositionState" attributename="PositionState" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,(,), ,,,,&quot;, &quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="AFeature" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,, [,],,,,,,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="AFeature" attributename="Sem" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,, ,,,,&quot;, &quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="AFeature" attributename="Gram" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,,,,,,&quot;, &quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="AFeature" attributename="Clue" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,, ,,,,&quot;, &quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Constructions" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,,,,,,&quot;,&quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Passive" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,,,,,,&quot;,&quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Impers" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,,,,,,&quot;,&quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Constructions" attributename="Passive" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,, ,,,,&quot;, &quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Constructions" attributename="Impers" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,,,, ,,,,&quot;, &quot;,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />